language: node_js
node_js:
- '0.12.7'
deploy:
  provider: heroku
  api_key:
    secure: LdP8m5LIzm7rtppzYvYwJf5/db6Mw55UrSuMJlQzNOgWD4jb9VSMtNMIDncO9nvzzj/xLkbT1ijEvxJUg3E3Wf2nEORC13RvioB2SAXCO4p1UdtkSR+fFQGtWzDYsTBG4dcQUWygMOGImnbkYscdXicLrsomPQ6CgCSa8ENqAg5WGAxTWMRPvuhwFS+3zBGrhn+Nqp9Fh4PQ/pqMar33DaVVNV5zqCRWT82aVi9cFg1RmJ91wNcgd+P0sqps7rHFZLHmm3xoljcuh/+ad+QVEVtphISOey4zpl56dxxAauCjoUD3InlPok+f8gMQ02mn9uirjoLSFATvXCwHzWpxQUmXAy7s5qMJMteEQTKzqtM5I7bPu2Aw15TIOOTypwKleeLoDrWQ3ZeBEqEHt46nqKMbiskYZ1fhFhgZsUKQx4CVXm7yHme3Nn6tzDZLU7H23OQKLJ0UiVoJc9nG2U8Y64OXaUs6VG5lAsiGWJWe5jaTxj2u4uTu72okfEX1ubuMVytPWgUCHY3G298Zbx30yBj4+MD4rxudnZrJOJmQVvgEIuxRGEow9mIwAh2+tHEmi8a+B7UZ90l2d9fU6T4MsSLT9sdX7tYgJQat2VqPGr8CdPA/iwjnPZEnjJnsQC7vf5jyvx2isZ9KCD4FltS/h/ub97k6lfy8/FxPub4Vbwk=
  app: hidden-sands-2214
  on:
    repo: indeterminatewoodchuck/indeterminatewoodchuck
